[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "assistant-agent"
version = "0.0.0"
description = ""
authors = ["tenzindelek <tenzdelek>",]
readme = "README.md"
packages = [{ include = "api" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.6"
sqlalchemy = "^2.0.36"
asyncpg = "^0.30.0"
alembic = "^1.14.0"
pydantic = "^2.10.6"
pydantic-settings = "^2.6.1"
psycopg2-binary = "^2.9.9"
python-dotenv = "^1.0.1"
python-jose = "^3.3.0"
pyjwt = "^2.10.0"
requests = "^2.32.3"
langchain-core = "^0.3.29"
langchain-anthropic = "^0.3.8"
langchain-openai = "^0.2.14"
langchain-google-genai = "^2.0.8"
langgraph = "^0.2.59"
httpx = "^0.28.1"
rich = "^14.3.1"
boto3 = "^1.35.0"
python-multipart = "^0.0.10"

[tool.poetry.scripts]
start = "uvicorn:main"

[tool.poetry.dependencies.uvicorn]
extras = [ "standard",]
version = "^0.32.1"
