"""remove file

Revision ID: 18cf46778420
Revises: ff67e0cb91ac
Create Date: 2026-02-24 16:14:26.704258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cf46778420'
down_revision: Union[str, Sequence[str], None] = 'ff67e0cb91ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
