"""added tokencount field in context table

Revision ID: 635acdc7f036
Revises: 18cf46778420
Create Date: 2026-02-25 14:29:23.227314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635acdc7f036'
down_revision: Union[str, Sequence[str], None] = '18cf46778420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context', 'token_count')
    # ### end Alembic commands ###
