"""added pecha field in context table

Revision ID: ff67e0cb91ac
Revises: 9abb7421d773
Create Date: 2026-02-10 16:58:08.793622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff67e0cb91ac'
down_revision: Union[str, Sequence[str], None] = '9abb7421d773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('pecha_title', sa.String(length=255), nullable=True))
    op.add_column('context', sa.Column('pecha_text_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context', 'pecha_text_id')
    op.drop_column('context', 'pecha_title')
    # ### end Alembic commands ###
