from __future__ import annotations

from .types import ModelSpec
from .providers.anthropic import build_anthropic
from .providers.openai import build_openai
from .providers.gemini import build_gemini
from .providers.dharmamitra import build_dharmamitra

REGISTRY: dict[str, ModelSpec] = {
    "claude-sonnet-4-20250514": ModelSpec(
        name="claude-sonnet-4-20250514",
        provider="Anthropic",
        required_credential="ANTHROPIC_API_KEY",
        build=build_anthropic,
        description="Claude Sonnet 4.0 (2025-05-14)",
        display_name="Claude Sonnet 4",
        capabilities=("text", "reasoning", "translation"),
        context_window=200000,
        aliases=(),
    ),
    "claude-3-5-haiku-20241022": ModelSpec(
        name="claude-3-5-haiku-20241022",
        provider="Anthropic",
        required_credential="ANTHROPIC_API_KEY",
        build=build_anthropic,
        description="Claude 3.5 Haiku (2024-10-22)",
        display_name="Claude 3.5 Haiku",
        capabilities=("text", "translation"),
        context_window=200000,
    ),
    "claude-3-opus-20240229": ModelSpec(
        name="claude-3-opus-20240229",
        provider="Anthropic",
        required_credential="ANTHROPIC_API_KEY",
        build=build_anthropic,
        description="Claude 3 Opus (2024-02-29)",
        display_name="Claude 3 Opus",
        capabilities=("text", "reasoning", "translation"),
        context_window=200000,
    ),
    "claude-haiku-4-5-20251001": ModelSpec(
        name="claude-haiku-4-5-20251001",
        provider="Anthropic",
        required_credential="ANTHROPIC_API_KEY",
        build=build_anthropic,
        description="Claude Haiku 4.5 (2025-10-01)",
        display_name="Claude Haiku 4.5",
        capabilities=("text", "reasoning", "translation", "advanced-reasoning"),
        context_window=200000,
    ),
    "claude-sonnet-4-5-20250929": ModelSpec(
        name="claude-sonnet-4-5-20250929",
        provider="Anthropic",
        required_credential="ANTHROPIC_API_KEY",
        build=build_anthropic,
        description="Claude Sonnet 4.5 (2025-09-29)",
        display_name="Claude Sonnet 4.5",
        capabilities=("text", "reasoning", "translation", "advanced-reasoning"),
        context_window=200000,
    ),
    "gpt-4": ModelSpec(
        name="gpt-4",
        provider="OpenAI",
        required_credential="OPENAI_API_KEY",
        build=build_openai,
        description="GPT-4",
        display_name="GPT-4",
        capabilities=("text", "reasoning", "translation"),
        context_window=128000,
    ),
    "gpt-4-turbo": ModelSpec(
        name="gpt-4-turbo",
        provider="OpenAI",
        required_credential="OPENAI_API_KEY",
        build=build_openai,
        description="GPT-4 Turbo",
        display_name="GPT-4 Turbo",
        capabilities=("text", "reasoning", "translation"),
        context_window=128000,
    ),
    "gpt-3.5-turbo": ModelSpec(
        name="gpt-3.5-turbo",
        provider="OpenAI",
        required_credential="OPENAI_API_KEY",
        build=build_openai,
        description="GPT-3.5 Turbo",
        display_name="GPT-3.5 Turbo",
        capabilities=("text", "translation"),
        context_window=16385,
    ),
    "gemini-2.5-pro": ModelSpec(
        name="gemini-2.5-pro",
        provider="Google",
        required_credential="GEMINI_API_KEY",
        build=build_gemini,
        description="Gemini 2.5 Pro",
        display_name="Gemini 2.5 Pro",
        capabilities=("text", "reasoning", "translation"),
        context_window=30720,
    ),
    "gemini-2.5-flash": ModelSpec(
        name="gemini-2.5-flash",
        provider="Google",
        required_credential="GEMINI_API_KEY",
        build=build_gemini,
        description="Gemini 2.5 Flash (fast)",
        display_name="Gemini 2.5 Flash",
        capabilities=("text", "reasoning", "translation"),
        context_window=30720,
    ),
    "gemini-2.5-flash-thinking": ModelSpec(
        name="gemini-2.5-flash-thinking",
        provider="Google",
        required_credential="GEMINI_API_KEY",
        build=build_gemini,
        description="Virtual: Gemini 2.5 Flash with thinking",
        display_name="Gemini 2.5 Flash Thinking",
        is_thinking=True,
        capabilities=("text", "reasoning", "translation"),
        context_window=30720,
        provider_model_name="gemini-2.5-flash",
        aliases=(),
    ),
    "gemini-pro-vision": ModelSpec(
        name="gemini-pro-vision",
        provider="Google",
        required_credential="GEMINI_API_KEY",
        build=build_gemini,
        description="Gemini Pro Vision",
        display_name="Gemini Pro Vision",
        capabilities=("text", "vision", "translation"),
        context_window=30720,
    ),
    "gemini-pro": ModelSpec(
        name="gemini-pro",
        provider="Google",
        required_credential="GEMINI_API_KEY",
        build=build_gemini,
        description="Gemini Pro",
        display_name="Gemini Pro",
        capabilities=("text", "reasoning", "translation"),
        context_window=30720,
    ),
    "dharamitra": ModelSpec(
        name="dharamitra",
        provider="Dharmamitra",
        required_credential="DHARMAMITRA_TOKEN",
        build=build_dharmamitra,
        description="Dharmamitra Chat Translate (mitra-base)",
        display_name="Dharmamitra",
        capabilities=("text", "translation"),
        context_window=None,
    ),
}

def resolve_model_name(name: str) -> str:
    return (name or "").strip().lower()
